Add header section
torqbit/html-css-templates pull request #1
Opened 2024-01-08 08:09 UTC by srikant96

2024-01-08 08:29 UTC, amezng requested changes
MTC

2024-01-08 08:29 UTC, amezng commented on blogs/01/index.html
> +        <nav class="header">
Use header element to wrap the nav element

2024-01-08 08:29 UTC, amezng commented on blogs/01/styles/header.css
> +}
Mobile view is incomplete. Complete the css for responsive design.

2024-01-08 17:59 UTC, srikant96 commented on blogs/01/styles/header.css
> +}
I used display none to remove the Ul element, in blog website only Mini blog is there is left side when  we switch  mobile view  . So  i just removed  removed ul section.

@media screen and (max-width:425px){
	nav.header>ul{
		display:none;
}
}

2024-01-08 17:59 UTC, srikant96 commented on blogs/01/index.html
> +        <nav class="header">
Done

2024-01-09 09:59 UTC, amezng commented on blogs/01/styles/header.css
> +}
What about the hamburger icon on the right side?

2024-01-10 08:11 UTC, srikant96 commented on blogs/01/styles/header.css
> +}
done

2024-01-10 14:07 UTC, merged