Add header
torqbit/html-css-templates pull request #17
Opened 2024-01-20 12:16 UTC by spriha1301

2024-01-20 13:12 UTC, itsashishbharti reviewed
pull the all yours entire html and css code of  header section

2024-01-20 13:12 UTC, itsashishbharti commented on blogs/01/styles/header.css
>      background-color:white;
use variable  for  background color

2024-01-20 13:15 UTC, itsashishbharti commented
share your mobile screenshot of header section

2024-01-20 13:15 UTC, amezng requested changes
- [ ] Upload the mobile view
- [ ] Use css variables

2024-01-20 13:15 UTC, amezng commented on blogs/01/index.html
> +                        <li><a href="#">tech</a></li>
Use `#home` as the href value. Similarly for all the other anchor elements

2024-01-21 15:41 UTC, spriha1301 commented
![mobile view](https://github.com/torqbit/html-css-templates/assets/155803903/f0dff979-6a9e-4500-820d-fa94ce8d95b4)

2024-01-23 05:52 UTC, itsashishbharti commented on blogs/01/styles/post-highlight-section-1.css
> +    div.boxes{
In header section html you not deleare any div with the class name .boxes why you use this

2024-01-23 13:07 UTC, amezng commented
not as per the design

2024-01-23 13:07 UTC, closed without merging