Added  post highlight section 1
torqbit/html-css-templates pull request #2
Opened 2024-01-08 08:47 UTC by srikant96

2024-01-08 09:23 UTC, amezng requested changes
MTC

2024-01-08 09:23 UTC, amezng commented on blogs/01/styles/post-highlight-section-1.css
> +    background-color: #f8f9fa!important;
Do not use `!important` flag.

2024-01-08 09:23 UTC, amezng commented on blogs/01/styles/post-highlight-section-1.css
> +    gap:20px;
align the margin attribute

2024-01-08 09:24 UTC, amezng commented
Add the screenshot of the section

2024-01-08 18:12 UTC, srikant96 commented on blogs/01/styles/post-highlight-section-1.css
> +    gap:20px;
Done

2024-01-08 18:12 UTC, srikant96 commented on blogs/01/styles/post-highlight-section-1.css
> +    background-color: #f8f9fa!important;
Done

2024-01-09 10:00 UTC, amezng approved these changes
LGTM

2024-01-09 10:00 UTC, merged