Added recent post section
torqbit/html-css-templates pull request #3
Opened 2024-01-08 09:01 UTC by srikant96

2024-01-08 09:26 UTC, amezng requested changes
MTC

2024-01-08 09:26 UTC, amezng commented on blogs/01/index.html
> +                    <div><img src= "https://placehold.co/345x200/violet/black" placeholder=""></div>
Close the img tag

2024-01-08 09:26 UTC, amezng commented on blogs/01/index.html
> +                    <div><img src= "https://placehold.co/345x200/violet/black" placeholder=""></div>
close the image tag

2024-01-08 09:26 UTC, amezng commented on blogs/01/styles/recent-post.css
> +    color: rgb(0, 0, 0);
Use hex code for the color

2024-01-08 09:26 UTC, amezng commented on blogs/01/styles/recent-post.css
> +    background-color: #8bc34a!important;
Don't use `!important`

2024-01-08 18:31 UTC, srikant96 commented on blogs/01/styles/recent-post.css
> +    color: rgb(0, 0, 0);
Done

2024-01-09 10:02 UTC, amezng commented
@srikant96 Resolve the conflicts

2024-01-10 14:24 UTC, amezng requested changes
MTC

2024-01-10 14:24 UTC, amezng commented on blogs/01/styles/recent-post.css
> +        height: 6650px;
height is redundant here

2024-01-10 14:24 UTC, amezng commented on blogs/01/styles/recent-post.css
> +    color: blue;
why using text-decoration none for div?

2024-01-10 14:24 UTC, amezng commented on blogs/01/styles/recent-post.css
> +    background-color: rgb(255, 255, 255);
Use hex code for the color code.

2024-01-12 07:58 UTC, closed without merging